# Usando una excepci√≥n
try:
  raise Exception("Hola mundo")
except Exception as e:
  print(e)